//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Collections.Specialized;
using System.Runtime.Serialization;


namespace FootballManagement.Commons.Entities
{
    [DataContract(IsReference = true)]
    public partial class Match
    {
        #region Primitive Properties
    	[DataMember]
    		[Required]
    	    public virtual int Id
        {
            get;
            set;
        }
    	[DataMember]
    		[Required]
    	    public virtual System.DateTime MatchDate
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
    	[DataMember]
        public virtual List<Card> Cards
        {
            get
            {
                if (_cards == null)
                {
                    _cards = new List<Card>();
                }
                return _cards;
            }
            set
            {
                _cards = value;
            }
        }
        private List<Card> _cards;
    
    	[DataMember]
        public virtual List<Goal> Goals
        {
            get
            {
                if (_goals == null)
                {
                    _goals = new List<Goal>();
                }
                return _goals;
            }
            set
            {
                _goals = value;
            }
        }
        private List<Goal> _goals;
    
    	[DataMember]
        public virtual Team Team
        {
            get { return _team; }
            set { _team = value; }
        }
        private Team _team;
    
    	[DataMember]
        public virtual Team Team1
        {
            get;
            set;
        }
    
    	[DataMember]
        public virtual Tournament Tournament
        {
            get { return _tournament; }
            set { _tournament = value; }
        }
        private Tournament _tournament;
    
    	[DataMember]
        public virtual List<Player> Players
        {
            get
            {
                if (_players == null)
                {
                    _players = new List<Player>();
                }
                return _players;
            }
            set
            {
                _players = value;
            }
        }
        private List<Player> _players;
    
    	[DataMember]
        public virtual List<Referee> Referees
        {
            get
            {
                if (_referees == null)
                {
                    _referees = new List<Referee>();
                }
                return _referees;
            }
            set
            {
                _referees = value;
            }
        }
        private List<Referee> _referees;

        #endregion

    }
}
