//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Collections.Specialized;
using System.Runtime.Serialization;


namespace FootballManagement.Commons.Entities
{
    [DataContract(IsReference = true)]
    public partial class Person
    {
        #region Primitive Properties
    	[DataMember]
    		[Required]
    	    public virtual int Id
        {
            get;
            set;
        }
    	[DataMember]
    		[Required]
    	    public virtual string Name
        {
            get;
            set;
        }
    	[DataMember]
    		[Required]
    	    public virtual string Gender
        {
            get;
            set;
        }
    	[DataMember]
    		[Required]
    	    public virtual System.DateTime Birthday
        {
            get;
            set;
        }

        #endregion

    }
}
