//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Collections.Specialized;
using System.Runtime.Serialization;


namespace FootballManagement.Commons.Entities
{
    [DataContract(IsReference = true)]
    public partial class Player : Person
    {
        #region Primitive Properties
    	[DataMember]
    		[Required]
    	    public virtual bool IsCaptain
        {
            get;
            set;
        }
    	[DataMember]
    		[Required]
    	    public virtual bool IsAuthorized
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
    	[DataMember]
        public virtual List<Card> Cards
        {
            get
            {
                if (_cards == null)
                {
                    _cards = new List<Card>();
                }
                return _cards;
            }
            set
            {
                _cards = value;
            }
        }
        private List<Card> _cards;
    
    	[DataMember]
        public virtual List<Goal> Goals
        {
            get
            {
                if (_goals == null)
                {
                    _goals = new List<Goal>();
                }
                return _goals;
            }
            set
            {
                _goals = value;
            }
        }
        private List<Goal> _goals;
    
    	[DataMember]
        public virtual Team Team
        {
            get { return _team; }
            set { _team = value; }
        }
        private Team _team;
    
    	[DataMember]
        public virtual List<Match> Matches
        {
            get
            {
                if (_matches == null)
                {
                    _matches = new List<Match>();
                }
                return _matches;
            }
            set
            {
                _matches = value;
            }
        }
        private List<Match> _matches;

        #endregion

    }
}
