//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Collections.Specialized;
using System.Runtime.Serialization;


namespace FootballManagement.Commons.Entities
{
    [DataContract(IsReference = true)]
    public partial class Referee : Person
    {
        #region Primitive Properties
    	[DataMember]
    		[Required]
    	    public virtual string Degree
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
    	[DataMember]
        public virtual List<Match> Matches
        {
            get
            {
                if (_matches == null)
                {
                    _matches = new List<Match>();
                }
                return _matches;
            }
            set
            {
                _matches = value;
            }
        }
        private List<Match> _matches;
    
    	[DataMember]
        public virtual List<Tournament> Tournaments
        {
            get
            {
                if (_tournaments == null)
                {
                    _tournaments = new List<Tournament>();
                }
                return _tournaments;
            }
            set
            {
                _tournaments = value;
            }
        }
        private List<Tournament> _tournaments;

        #endregion

    }
}
