//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Collections.Specialized;
using System.Runtime.Serialization;


namespace FootballManagement.Commons.Entities
{
    [DataContract(IsReference = true)]
    public partial class Tournament
    {
        #region Primitive Properties
    	[DataMember]
    		[Required]
    	    public virtual int Id
        {
            get;
            set;
        }
    	[DataMember]
    		[Required]
    	    public virtual string Name
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
    	[DataMember]
        public virtual List<Match> Matches
        {
            get
            {
                if (_matches == null)
                {
                    _matches = new List<Match>();
                }
                return _matches;
            }
            set
            {
                _matches = value;
            }
        }
        private List<Match> _matches;
    
    	[DataMember]
        public virtual List<Team> Teams
        {
            get
            {
                if (_teams == null)
                {
                    _teams = new List<Team>();
                }
                return _teams;
            }
            set
            {
                _teams = value;
            }
        }
        private List<Team> _teams;
    
    	[DataMember]
        public virtual List<Referee> Referees
        {
            get
            {
                if (_referees == null)
                {
                    _referees = new List<Referee>();
                }
                return _referees;
            }
            set
            {
                _referees = value;
            }
        }
        private List<Referee> _referees;

        #endregion

    }
}
