//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.EntityClient;
using FootballManagement.Commons.Entities;

namespace FootballManagement.Data
{
    public partial class FootballManagementEntities : ObjectContext
    {
        public const string ConnectionString = "name=FootballManagementEntities";
        public const string ContainerName = "FootballManagementEntities";
    
        #region Constructors
    
        public FootballManagementEntities()
            : base(ConnectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = false;
    		this.ContextOptions.ProxyCreationEnabled = false;
        }
    
        public FootballManagementEntities(string connectionString)
            : base(connectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = false;
    		this.ContextOptions.ProxyCreationEnabled = false;
        }
    
        public FootballManagementEntities(EntityConnection connection)
            : base(connection, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = false;
    		this.ContextOptions.ProxyCreationEnabled = false;
        }
    
        #endregion
    
        #region ObjectSet Properties
    
        public ObjectSet<Card> Cards
        {
            get { return _cards  ?? (_cards = CreateObjectSet<Card>("Cards")); }
        }
        private ObjectSet<Card> _cards;
    
        public ObjectSet<Goal> Goals
        {
            get { return _goals  ?? (_goals = CreateObjectSet<Goal>("Goals")); }
        }
        private ObjectSet<Goal> _goals;
    
        public ObjectSet<Match> Matches
        {
            get { return _matches  ?? (_matches = CreateObjectSet<Match>("Matches")); }
        }
        private ObjectSet<Match> _matches;
    
        public ObjectSet<Person> People
        {
            get { return _people  ?? (_people = CreateObjectSet<Person>("People")); }
        }
        private ObjectSet<Person> _people;
    
        public ObjectSet<Team> Teams
        {
            get { return _teams  ?? (_teams = CreateObjectSet<Team>("Teams")); }
        }
        private ObjectSet<Team> _teams;
    
        public ObjectSet<Tournament> Tournaments
        {
            get { return _tournaments  ?? (_tournaments = CreateObjectSet<Tournament>("Tournaments")); }
        }
        private ObjectSet<Tournament> _tournaments;

        #endregion

    }
}
